kind = "mobile"
previewPath = "/mobile/"
title = "IIC Mobile"
version = "1.0.0"
id = "artifacts/iic-app-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 21072

[services.development]
run = "pnpm --filter @workspace/iic-app-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/iic-app-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/iic-app-mobile", "run", "serve" ]

[services.env]
PORT = "21072"
BASE_PATH = "/mobile/"
